In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Carregue o conjunto de dados Iris
from sklearn.datasets import load_iris
iris = load_iris()
data = iris.data
target = iris.target

# Converta os dados em um DataFrame para facilitar a manipulação
iris_df = pd.DataFrame(data, columns=iris.feature_names)
iris_df['target'] = target

In [2]:
# Divida o conjunto de dados em treinamento (80%) e teste (20%)
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=42)

In [3]:
# Crie o classificador Naive Bayes Gaussiano
nb_classifier = GaussianNB()

# Ajuste o modelo aos dados de treinamento
nb_classifier.fit(X_train, y_train)

GaussianNB()

In [4]:
# Faça previsões no conjunto de teste
y_pred = nb_classifier.predict(X_test)

# Avalie a precisão do modelo
accuracy = accuracy_score(y_test, y_pred)
print(f"Acurácia: {accuracy:.2f}")

# Exiba a matriz de confusão e o relatório de classificação
confusion = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=iris.target_names)
print("Matriz de Confusão:")
print(confusion)
print("\nRelatório de Classificação:")
print(report)

Acurácia: 1.00
Matriz de Confusão:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Relatório de Classificação:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

